services:
  rust:
    image: rust:latest
    #build: .
    container_name: rust_container
    volumes:
      - ../projects:/projects/
    working_dir: /projects
    user: root
    #entrypoint: ["/entrypoint.sh"]
    